forward_channel = 'https://t.me/mychannel'
pattern = '\bmoonduck1[67]\b'

session = 'tgwatch'
api_id = 1234567
api_hash = 'hash'

[admins.moonduck16]
id = 123456

[admins.moonduck17]
id = 1234567
